-- Active: 1691456479247@@127.0.0.1@3306@sucos_vendas
DROP PROCEDURE IF EXISTS p_calculo_faturamento;
DELIMITER $$
    CREATE PROCEDURE p_calculo_faturamento()
        BEGIN
            DELETE FROM TAB_FATURAMENTO;
            INSERT INTO TAB_FATURAMENTO
            SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM
            NOTAS_FISCAIS A INNER JOIN ITENS_NOTAS_FISCAIS B
            ON A.NUMERO = B.NUMERO
            GROUP BY A.DATA_VENDA;
        END$$
DELIMITER;