-- Active: 1691456479247@@127.0.0.1@3306@vendas_sucos
CREATE TABLE PRODUTOS2(
    CODIGO VARCHAR(10) NOT NULL,
    DESCRITOR VARCHAR(100) NULL,
    SABOR VARCHAR(50) NULL,
    TAMANHO VARCHAR(50) NULL,
    EMBALAGEM VARCHAR(50),
    PRECO_LISTA FLOAT NULL,
    PRIMARY KEY(CODIGO)
);

INSERT INTO produtos2
SELECT * FROM produtos;

SELECT * FROM produtos2 LIMIT 5;

-- UPDATE sem WHERE
UPDATE produtos2 SET `PRECO_LISTA` = 15;

-- DELETE sem WHERE
DELETE FROM produtos2;

DROP TABLE produtos2;

-- Exercício: NOTAS e ITENS_NOTAS
DELETE FROM notas;
DELETE FROM itens_notas;