-- Active: 1691456479247@@127.0.0.1@3306@sucos_vendas
CREATE TABLE TAB_FATURAMENTO (DATA_VENDA DATE NULL, TOTAL_VENDA FLOAT);

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_INSERT 
  AFTER INSERT ON ITENS_NOTAS_FISCAIS
  FOR EACH ROW BEGIN
  CALL p_calculo_faturamento();
END//

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_UPDATE 
  AFTER UPDATE ON ITENS_NOTAS_FISCAIS
  FOR EACH ROW BEGIN
  CALL p_calculo_faturamento();
END//

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_DELETE 
  AFTER DELETE ON ITENS_NOTAS_FISCAIS
  FOR EACH ROW BEGIN
  CALL p_calculo_faturamento();
END//

DELIMITER ;

DROP TRIGGER TG_CALCULA_FATURAMENTO_INSERT;
DROP TRIGGER TG_CALCULA_FATURAMENTO_UPDATE;
DROP TRIGGER TG_CALCULA_FATURAMENTO_DELETE;

CALL p_inserir_venda('2023-08-24', 3, 100);
CALL p_inserir_venda('2023-08-21', 2, 50);

SELECT * FROM tab_faturamento 
  WHERE DATA_VENDA = '2023-08-21' 
  OR DATA_VENDA = '2023-08-24';
