CREATE VIEW VW_SOMA_EMBALAGENS AS
    SELECT 
        EMBALAGEM,
        SUM(PRECO_DE_LISTA) AS SOMA_PRECO
        FROM TABELA_DE_PRODUTOS
        GROUP BY EMBALAGEM;

SELECT EMBALAGEM, SOMA_PRECO
    FROM VW_SOMA_EMBALAGENS
    WHERE SOMA_PRECO >= 80;

----------------------------------------------------------------------------------------------------------

-- ATIVIDADE

-- 01. Usando a visão para substituir o HAVING

-- Veja a consulta abaixo, que foi resposta de uma atividade anterior:

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

-- Redesenhe esta consulta, criando uma visão para a lista de quantidades totais por produto
-- e aplicando a condição e ordenação sobre essa mesma visão.

--Minha resposta:

CREATE VIEW VW_PRODUTOS_MAIS_VENDIDOS AS
    SELECT 
        CODIGO_DO_PRODUTO,
        SUM(QUANTIDADE) AS QUANTIDADE_VENDIDA
        FROM ITENS_NOTAS_FISCAIS
        GROUP BY 
            CODIGO_DO_PRODUTO
        ORDER BY 
            SUM(QUANTIDADE) DESC;

SELECT * FROM VW_PRODUTOS_MAIS_VENDIDOS WHERE QUANTIDADE_VENDIDA > 394000;

SELECT 
    VW_PMV.CODIGO_DO_PRODUTO,
    TB.NOME_DO_PRODUTO,
    VW_PMV.QUANTIDADE_VENDIDA
    FROM VW_PRODUTOS_MAIS_VENDIDOS VW_PMV
    INNER JOIN TABELA_DE_PRODUTOS TB
    ON VW_PMV.CODIGO_DO_PRODUTO = TB.CODIGO_DO_PRODUTO
    WHERE QUANTIDADE_VENDIDA > 394000;

