-- Active: 1691456479247@@127.0.0.1@3306@vendas_sucos
DELIMITER //

CREATE TRIGGER TG_CALCULA_FATURAMENTO_UPDATE AFTER UPDATE ON ITENS_NOTAS
FOR EACH ROW BEGIN
    
    DELETE FROM tab_faturamento;

    INSERT INTO tab_faturamento
        SELECT NF.DATA_VENDA, 
        SUM(INF.QUANTIDADE * INF.PRECO) AS TOTAL_VENDAS 
        FROM notas NF INNER JOIN itens_notas INF
        ON NF.NUMERO = INF.NUMERO
        GROUP BY NF.DATA_VENDA;

END //

DELIMITER //

CREATE TRIGGER TG_CALCULA_FATURAMENTO_DELETE AFTER DELETE ON ITENS_NOTAS
FOR EACH ROW BEGIN
    
    DELETE FROM tab_faturamento;

    INSERT INTO tab_faturamento
        SELECT NF.DATA_VENDA, 
        SUM(INF.QUANTIDADE * INF.PRECO) AS TOTAL_VENDAS 
        FROM notas NF INNER JOIN itens_notas INF
        ON NF.NUMERO = INF.NUMERO
        GROUP BY NF.DATA_VENDA;

END //

SELECT * FROM notas;
SELECT * FROM itens_notas;

UPDATE itens_notas SET QUANTIDADE = 200 WHERE NUMERO = '0102';

DELETE FROM itens_notas WHERE NUMERO = '0101' AND CODIGO = '1002334';

SELECT * FROM tab_faturamento;