SELECT * FROM TABELA_DE_CLIENTES;

SELECT * 
    FROM NOTAS_FISCAIS NF
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON NF.NUMERO = INF.NUMERO
    WHERE ROWNUM < 10;

SELECT NF.CPF,
    TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM NOTAS_FISCAIS NF
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON NF.NUMERO = INF.NUMERO
    GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY');

SELECT 
    TC.CPF, 
    TC.NOME, 
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL
    FROM TABELA_DE_CLIENTES TC
    INNER JOIN (
        SELECT NF.CPF,
        TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
        FROM NOTAS_FISCAIS NF
        INNER JOIN ITENS_NOTAS_FISCAIS INF
        ON NF.NUMERO = INF.NUMERO
        GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')) TV
    ON TV.CPF = TC.CPF;

SELECT 
    TC.CPF, 
    TC.NOME,
    TV.MES_ANO, 
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL,
    (
        CASE 
            WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL
                THEN 'VENDAS VÁLIDAS'
                ELSE 'VENDAS INVÁLIDAS'
        END
    ) AS RESULTADO
    FROM TABELA_DE_CLIENTES TC
    INNER JOIN (
        SELECT NF.CPF,
        TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
        FROM NOTAS_FISCAIS NF
        INNER JOIN ITENS_NOTAS_FISCAIS INF
        ON NF.NUMERO = INF.NUMERO
        GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')) TV
    ON TV.CPF = TC.CPF
    WHERE TV.MES_ANO = '01-2016'
    ORDER BY RESULTADO DESC;

---------------------------------------------------------------------------------

-- ATIVIDADE

-- 01.  Complementando o relatório

-- Complemente este relatório, listando somente os que tiveram vendas inválidas 
-- e calculando a diferença entre o limite de venda máximo e o realizado, em percentuais.

-- Minha resposta:
SELECT 
    TC.CPF, 
    TC.NOME,
    TV.MES_ANO, 
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL,
    (
        ROUND(((1 - (TC.VOLUME_DE_COMPRA / TV.QUANTIDADE_TOTAL )) * 100), 2)
    ) AS PERCENTUAL,
    (
        CASE 
            WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL
                THEN 'VENDAS VÁLIDAS'
                ELSE 'VENDAS INVÁLIDAS'
        END
    ) AS RESULTADO
    FROM TABELA_DE_CLIENTES TC
    INNER JOIN (
        SELECT NF.CPF,
        TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
        FROM NOTAS_FISCAIS NF
        INNER JOIN ITENS_NOTAS_FISCAIS INF
        ON NF.NUMERO = INF.NUMERO
        GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')) TV
    ON TV.CPF = TC.CPF
    WHERE TV.MES_ANO = '01-2016'
        AND (TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0
    ORDER BY RESULTADO DESC;