
INSERT INTO TB_PRODUTOS 
(
    PRODUTO,
    NOME,
    EMBALAGEM,
    TAMANHO,
    SABOR,
    PRECO_LISTA
)
VALUES
('1040107', 'Light - 350 ml - Melância', 'Lata', '350 ml', 'Melância', 4.56);

INSERT INTO TB_PRODUTOS 
(
    PRODUTO,
    NOME,
    EMBALAGEM,
    TAMANHO,
    SABOR,
    PRECO_LISTA
)
VALUES
('1037797', 'Clean - 2 Litros - Laranja', 'PET', '2 litros', 'Laranja', 16.01);

-- Atividade: Incluindo outros vendedores

-- Minha resposta:

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00400', 'Maria do Rosario', '23-JUL-2012', 0.15);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00810', 'Marcia Almeida', '14-DEC-2016', 0.18);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00414', 'Carlos Moreira', '13-NOV-2015', 0.14);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00934', 'Juvenildo Martins', '09-MAR-2010', 0.20);

SELECT * FROM TB_VENDEDORES;
