UPDATE TB_PRODUTOS SET EMBALAGEM = 'Lata' WHERE PRODUTO = '1037797';

UPDATE TB_PRODUTOS SET 
    NOME = 'Clean - 350 ml - Laranja',
    TAMANHO = '350 ml',
    PRECO_LISTA = 5.50
    WHERE PRODUTO = '1037797';

SELECT * FROM TB_PRODUTOS;

-- Atividade: Alterando comissões de vendedores

-- Minha resposta:

SELECT * FROM TB_VENDEDORES ORDER BY DATA_ADMISSAO ASC;

UPDATE TB_VENDEDORES
  SET PERCENTUAL_COMISSAO = 0.18
WHERE MATRICULA = '00400' 
    OR MATRICULA = '00414'
    OR MATRICULA = '00810';