-- ATIVIDADE

-- 01.  Nome dos produtos
-- Além dos produtos que venderam mais que 394000 litros, exibir os  nomes dos produtos.

-- Minha Resposta:

SELECT INF.CODIGO_DO_PRODUTO, TBP.NOME_DO_PRODUTO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDIDA
    FROM ITENS_NOTAS_FISCAIS INF
    INNER JOIN TABELA_DE_PRODUTOS TBP
    ON INF.CODIGO_DO_PRODUTO = TBP.CODIGO_DO_PRODUTO
    GROUP BY INF.CODIGO_DO_PRODUTO, TBP.NOME_DO_PRODUTO
    HAVING SUM(INF.QUANTIDADE) > 394000
    ORDER BY QUANTIDADE_VENDIDA DESC;