-- RETORNA:
-- 03 VENDEDORES
-- 07 CLIENTES
SELECT DISTINCT
    TV.NOME AS NOME_VENDEDOR,
    TV.BAIRRO AS TV_BAIRRO,
    TC.NOME AS NOME_CLIENTE,
    TC.BAIRRO AS TC_BAIRRO
    FROM TABELA_DE_CLIENTES TC
    INNER JOIN TABELA_DE_VENDEDORES TV
    ON TV.BAIRRO = TC.BAIRRO
    ORDER BY NOME_VENDEDOR;

-- RETORNA 04 VENDEDORES
SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;

-- Testando o LEFT JOIN:
SELECT DISTINCT
    TV.NOME AS NOME_VENDEDOR,
    TV.BAIRRO AS TV_BAIRRO,
    TC.NOME AS NOME_CLIENTE,
    TC.BAIRRO AS TC_BAIRRO
    FROM TABELA_DE_CLIENTES TC
    LEFT JOIN TABELA_DE_VENDEDORES TV
    ON TV.BAIRRO = TC.BAIRRO
    ORDER BY NOME_VENDEDOR;
-- Retorna: todos os clientes, mas que não tem vendedores nesses bairros

-- Testando o RIGHT JOIN:
SELECT DISTINCT
    TV.NOME AS NOME_VENDEDOR,
    TV.BAIRRO AS TV_BAIRRO,
    TC.NOME AS NOME_CLIENTE,
    TC.BAIRRO AS TC_BAIRRO
    FROM TABELA_DE_CLIENTES TC
    RIGHT JOIN TABELA_DE_VENDEDORES TV
    ON TV.BAIRRO = TC.BAIRRO
    ORDER BY NOME_VENDEDOR;
-- Retorna: todos os vendedores, mas mostra que não existe um escritório para aquele bairro

-- Testando o FULL JOIN:
SELECT DISTINCT
    TV.NOME AS NOME_VENDEDOR,
    TV.BAIRRO AS TV_BAIRRO,
    TC.NOME AS NOME_CLIENTE,
    TC.BAIRRO AS TC_BAIRRO
    FROM TABELA_DE_CLIENTES TC
    FULL JOIN TABELA_DE_VENDEDORES TV
    ON TV.BAIRRO = TC.BAIRRO
    ORDER BY NOME_VENDEDOR;
-- Retorna o resultado da junção de RIGHT e LEFT JOIN