-- 12 BAIRROS
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;

-- 04 BAIRROS
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

-- 16 BAIRROS DISTINTOS
SELECT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION
SELECT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES  ORDER BY ORIGEM;

-- 20 BAIRROS
SELECT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION ALL
SELECT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES ORDER BY ORIGEM;