-- Active: 1691456479247@@127.0.0.1@3306@vendas_sucos
CREATE TABLE VENDAS(
    NUMERO VARCHAR(5) NOT NULL,
    DATA_VENDA DATE NULL,
    CPF VARCHAR(11) NOT NULL,
    MATRICULA VARCHAR(5) NOT NULL,
    IMPOSTO FLOAT NULL,
    PRIMARY KEY(NUMERO)
);

ALTER TABLE vendas
ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY(CPF) REFERENCES cliente (CPF);

ALTER TABLE vendas
ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY(MATRICULA) REFERENCES vendedores (MATRICULA);

DESC VENDAS;
