-- Active: 1691456479247@@127.0.0.1@3306@vendas_sucos
CREATE TABLE ITENS_NOTAS(
    NUMERO VARCHAR(5) NOT NULL,
    CODIGO_PRODUTO VARCHAR(10) NOT NULL,
    QUANTIDADE INT NULL,
    PRECO FLOAT NULL,
    PRIMARY KEY(NUMERO, CODIGO_PRODUTO)
);

ALTER TABLE itens_notas RENAME COLUMN CODIGO_PRODUTO TO CODIGO;

ALTER TABLE itens_notas
ADD CONSTRAINT FK_NOTAS
FOREIGN KEY(NUMERO)
REFERENCES notas (NUMERO);

ALTER TABLE itens_notas
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO)
REFERENCES produtos (CODIGO);

DESC ITENS_NOTAS;