-- Active: 1691456479247@@127.0.0.1@3306@vendas_sucos
CREATE TABLE PRODUTOS(
    CODIGO VARCHAR(10) NOT NULL,
    DESCRITOR VARCHAR(100) NULL,
    SABOR VARCHAR(50) NULL,
    TAMANHO VARCHAR(50) NULL,
    EMBALAGEM VARCHAR(50),
    PRECO_LISTA FLOAT NULL,
    PRIMARY KEY(CODIGO)
);

CREATE TABLE VENDEDORES(
    MATRICULA VARCHAR(5) NOT NULL,
    NOME VARCHAR(100) NULL,
    BAIRRO VARCHAR(50) NULL,
    COMISSAO FLOAT NULL,
    DATA_DE_ADIMISSAO DATE NULL,
    FERIAS BIT(1) NULL,
    PRIMARY KEY(MATRICULA)
);

ALTER TABLE vendedores
RENAME COLUMN DATA_DE_ADIMISSAO TO DATA_DE_ADMISSAO;

DESC PRODUTOS;
DESC VENDEDORES;

CREATE TABLE CLIENTE(
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(100) NULL,
    ENDERECO VARCHAR(150) NULL,
    BAIRRO VARCHAR(50) NULL,
    CIDADE VARCHAR(50) NULL,
    ESTADO VARCHAR(50) NULL,
    CEP VARCHAR(8) NULL,
    DATA_DE_NASCIMENTO DATE NULL,
    IDADE INT NULL,
    SEXO VARCHAR(1) NULL,
    LIMITE_DE_CREDITO FLOAT NULL,
    VOLUME_DE_COMPRA FLOAT NULL,
    PRIMEIRA_COMPRA BIT(1) NULL,
    PRIMARY KEY(CPF)
) ENGINE = InnoDB;

DESC cliente;