CREATE TABLE TB_CLIENTE (
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    ENDERECO1 VARCHAR2(150),
    ENDERECO2 VARCHAR2(150),
    BAIRRO VARCHAR2(50),
    CIDADE VARCHAR2(50),
    ESTADO VARCHAR2(2),
    CEP VARCHAR2(8),
    DATA_DE_NASCIMENTO DATE,
    IDADE INTEGER,
    SEXO VARCHAR2(1),
    LIMITE_CREDITO NUMBER(15, 2),
    VOLUME_COMPRA NUMBER,
    PRIMERA_COMPRA NUMBER(1)
);

-- Tarefa: Criando a tabela de vendedores
CREATE TABLE TB_VENDEDORES (
    MATRICULA VARCHAR2(5),
    NOME VARCHAR2(100),
    DATA_ADMISSAO DATE,
    PERCENTUAL_COMISSAO NUMBER(2, 2)
);

CREATE TABLE TB_PRODUTOS (
    PRODUTO VARCHAR2(20),
    NOME VARCHAR2(150),
    EMBALAGEM VARCHAR2(50),
    TAMANHO VARCHAR2(50),
    SABOR VARCHAR2(50),
    PRECO_LISTA NUMBER
);