CREATE TABLE TB_CLIENTE2 (
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    ENDERECO1 VARCHAR2(150),
    ENDERECO2 VARCHAR2(150),
    BAIRRO VARCHAR2(50),
    CIDADE VARCHAR2(50),
    ESTADO VARCHAR2(2),
    CEP VARCHAR2(8),
    DATA_DE_NASCIMENTO DATE,
    IDADE INTEGER,
    SEXO VARCHAR2(1),
    LIMITE_CREDITO NUMBER(15, 2),
    VOLUME_COMPRA NUMBER,
    PRIMERA_COMPRA NUMBER(1)
);

DESC TB_CLIENTE2;

DROP TABLE TB_CLIENTE2;